### ISSUE TITLE
Error - wpgraphql is undefined

### ISSUE THREAD

**Issue by parthp1808** [henrikwirth/gatsby-starter-wordpress-advanced#2]
` ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPagesStatefully lifecycle:

Cannot read property 'wpgraphql' of undefined

   6 | exports.createPagesStatefully = async ({ graphql, actions, reporter }, options) => {
   7 |
>  8 |   await createPages({ actions, graphql, reporter }, options)
     |   ^
   9 |   await createPosts({ actions, graphql, reporter }, options)
  10 | }
  11 |

File: gatsby-node.js:8:3`

What I did - 

-> Cloned the repo
-> npm install
-> created .env.development and entered wordpress url
-> gatsby develop returns above error
-> hardcoded wordpress url but still error remains
-> ran `npm install dotenv gatsby-source-graphql` (thought had to install them separately)
-> still error remains

**Comment by henrikwirth** [comment]
Is WPGraphQL installed properly? Did you check the settings for permalinks? 

Did you try to reach the endpoint with something else than Gatsby? For some reason it seems it is not able to reach your GraphQL endpoint.

**Comment by henrikwirth** [comment]
And make sure the .env.development looks something like this:
```
WORDPRESS_URL=http://gatsby-starter-wordpress-advanced.local
```

So the URL should not have an ending slash (/)

**Comment by stefanfmeyer** [comment]
I am having the same issue, Pulled all from Repo, added my wp-graphql endpoint that was setup during your tutorial, yet I am receiving the following errors:

>  ERROR #85923  GRAPHQL
> 
> There was an error in your GraphQL query:
> 
> Cannot query field "sourceUrl" on type "WPGraphQL_NodeWithFeaturedImageToMediaItemConnectionEdge".


> ERROR #85923  GRAPHQL
> 
> There was an error in your GraphQL query:
> 
> Cannot query field "altText" on type "WPGraphQL_NodeWithFeaturedImageToMediaItemConnectionEdge".



> ERROR #85923  GRAPHQL
> 
> There was an error in your GraphQL query:
> 
> Cannot query field "imageFile" on type "WPGraphQL_NodeWithFeaturedImageToMediaItemConnectionEdge".


 ERROR #11321  PLUGIN

"gatsby-node.js" threw and error while running the createPagesStatefully lifecycle:

Cannot read property 'wpgraphql' of undefined


What can you recommend I try? I have followed all steps meticulously from your tutorial

**Comment by henrikwirth** [comment]
Hi @stefanfmeyer.

This tutorial is pretty outdated. A lot has changed and it is advised to use this new plugin: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental

There is another starter project I made also some time back that works with that plugin: https://github.com/henrikwirth/gatsby-starter-wordpress-twenty-twenty

Or checkout the starters in the documentation here: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/themes-starters-examples.md
